simclr:
  # train options
  seed: 42 # sacred handles automatic seeding when passed in the config
  batch_size: 128
  start_epoch: 0
  epochs: 100
  pretrain: True
  learning_rate: 0.0003
  learning_rate_weights: 0.2
  learning_rate_biases: 0.0048

  # model options
  resnet: "resnet50"
  projection_dim: 64 # "[...] to project the representation to a 128-dimensional latent space"

  # loss options
  optimizer: "LARS" # or LARS (experimental)
  weight_decay: 1.0e-6 # "optimized using LARS [...] and weight decay of 10−6"
  temperature: 0.5 # see appendix B.7.: Optimal temperature under different batch sizes

  # logistic regression options
  logistic_batch_size: 256
  logistic_epochs: 500

barlow_twins:
  # train options
  seed: 42 # sacred handles automatic seeding when passed in the config
  batch_size: 128
  start_epoch: 0
  epochs: 100
  pretrain: True 
  learning_rate: 0.003 # Used for Adam optimizer 
  learning_rate_weights: 0.2
  learning_rate_biases: 0.0048

  # model options
  resnet: "resnet50"
  projector: '8192-8192-8192'
  lambd: 0.0051

  # loss options
  optimizer: "LARS" # or LARS (experimental)
  weight_decay: 1.0e-6 # "optimized using LARS [...] and weight decay of 10−6"

  # logistic regression options
  logistic_batch_size: 256
  logistic_epochs: 500
